Repository MARKETProtocol/website, pull requests merged in 2018-05, with the labels that each got.

#74 Fixes: https://github.com/MARKETProtocol/website/issues/73
  src/components/Footer.tsx
Labels: Status: Review Needed

#76 Add new team member
  src/assets/images/team/index.js
  src/assets/images/team/robert-jordan.svg
  src/containers/Team/config.ts
Labels: Priority: Medium, Status: In Progress

#79 Add sitemap
  makefile
  package-lock.json
  package.json
  public/docs_sitemap.xml
  public/robots.txt
  public/sitemap.xml
  scripts/sitemap.js
Labels: Priority: High, Status: Revision Needed

#86 Add an /about page to app
  src/assets/images/about/Group 13.svg
  src/assets/images/about/custody.svg
  src/assets/images/about/ethereum_blockchain.svg
  src/assets/images/about/header.svg
  src/assets/images/about/hedging.svg
  src/assets/images/about/mobile.svg
  src/assets/images/about/protocol.svg
  src/assets/images/about/short_selling.svg
  src/assets/images/about/timeline-mobile.svg
  src/assets/images/about/timeline-mobile1.svg
  src/assets/images/about/timeline-mobile2.svg
  src/assets/images/about/timeline.svg
  src/components/About/Banner.tsx
  src/components/About/Derivatives.tsx
  src/components/About/Opensource.tsx
  src/components/About/Timeline.tsx
  src/components/About/Trading.tsx
  src/components/Cta.tsx
  src/containers/About.tsx
  static.config.js
  test/components/About/Banner.test.tsx
  test/components/About/Derivatives.test.tsx
  test/components/About/Opensource.test.tsx
  test/components/About/Timeline.test.tsx
  test/components/About/Trading.test.tsx
  test/containers/About.test.tsx
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#91 Add new /partners page to website
  src/assets/images/partners/amadeus.png
  src/assets/images/partners/dg.png
  src/assets/images/partners/haven.png
  src/assets/images/partners/index.js
  src/assets/images/partners/maker.png
  src/assets/images/partners/partner_header.svg
  src/assets/images/partners/virtuse.png
  src/components/Cta.tsx
  src/components/Navbar.tsx
  src/components/NewsletterSubscribeBanner.tsx
  src/components/SocialLinks.tsx
  src/containers/Partners/config.ts
  src/containers/Partners/index.tsx
  src/containers/Team/index.tsx
  static.config.js
  test/MarketSubscriberForm.test.tsx
  test/components/NewsletterSubscribeBanner.test.tsx
  test/components/SocialLinks.test.tsx
  test/containers/Partners/Partners.test.tsx
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement
